services:
  mysql:
    container_name: demo_mysql_database
    image: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/data:/var/lib/mysql
  redis:
    container_name: demo_redis
    image: redis
    ports:
      - "16379:6379"