version: "3"
services:
  postgres:
    container_name: demo_postgres
    image: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
  redis:
    container_name: demo_redis
    image: redis
    ports:
      - "16379:6379"