server:
  port: 10110

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/demo
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间