### get all project
GET /api/project/all
Host: {{host}}:{{port}}

### create project
POST /api/project/create
Host: {{host}}:{{port}}
Content-Type: application/json

{
    "name": "Golden Retriever"
}

### update project
PUT /api/project/update?id=1555254607108771840
Host: {{host}}:{{port}}
Content-Type: application/json

{
    "name": "Border Collie"
}

### delete project
DELETE /api/project/delete?id=1555254607108771840
Host: {{host}}:{{port}}